[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "jinja"
file-types = ["j2"]
language-servers = ["tailwindcss-ls", "vscode-html-language-server"]

[[language]]
name = "tera"
file-types = ["tera"]
language-servers = ["tailwindcss-ls", "vscode-html-language-server"]

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["pyrefly"]
auto-format = true

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]
